# Background opacity and blur settings
#background_opacity 0.3
#background_blur 1

term xterm-kitty

enable_audio_bell no

# OS-specific tweaks (GNOME window decorations for X11)
linux_display_server X11

font_family Iosevka Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

url_color #0087bd
url_style curly
detect_urls yes

map ctrl+shift+backspace change_font_size all 0

cursor #ff9203
cursor_shape underline
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

scrollback_lines 5000
wheel_scroll_multiplier 3.0
map pageup scroll_page_up
map pagedown scroll_page_down

mouse_hide_wait -1

remember_window_size no

# (Monitor Width / 2 ) - gap*3
initial_window_width 942
# initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations yes


# Window management commands
# map ctrl+shift+enter discard_event
# map ctrl+shift+] discard_event
# map ctrl+shift+[ discard_event

# Layout management commands
# map ctrl+shift+l discard_event
# map ctrl+alt+r discard_event
# map ctrl+alt+s discard_event 

# Tab bar customization
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style bold
inactive_tab_font_style normal

# Tab management commands
# map ctrl+shift+t discard_event
# map ctrl+shift+right discard_event
# map ctrl+shift+left discard_event
# map ctrl+shift+q discard_event
# map ctrl+shift+t new_tab
# map ctrl+shift+right next_tab
# map ctrl+shift+left previous_tab
# map ctrl+shift+q close_tab

include themes/cyberdream.conf
